// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb4SJFM06LzS3AO5JD1wDXKNpqcJY5Nd4',
    appId: '1:842149269614:web:4100584d0793b1381ad67f',
    messagingSenderId: '842149269614',
    projectId: 'eitherofeisa',
    authDomain: 'eitherofeisa.firebaseapp.com',
    storageBucket: 'eitherofeisa.appspot.com',
    measurementId: 'G-5KKG1EF1PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcLyBMaDcL97SGazsHqfyBsMKmuOPVdA4',
    appId: '1:842149269614:android:d204f5ed0a1f0f961ad67f',
    messagingSenderId: '842149269614',
    projectId: 'eitherofeisa',
    storageBucket: 'eitherofeisa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkqThkvMUKFV9s3BPOB2UqBHx-yXCJ4Jw',
    appId: '1:842149269614:ios:6cb2fdd841d313191ad67f',
    messagingSenderId: '842149269614',
    projectId: 'eitherofeisa',
    storageBucket: 'eitherofeisa.appspot.com',
    iosBundleId: 'com.example.munimuniohagi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkqThkvMUKFV9s3BPOB2UqBHx-yXCJ4Jw',
    appId: '1:842149269614:ios:6cb2fdd841d313191ad67f',
    messagingSenderId: '842149269614',
    projectId: 'eitherofeisa',
    storageBucket: 'eitherofeisa.appspot.com',
    iosBundleId: 'com.example.munimuniohagi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb4SJFM06LzS3AO5JD1wDXKNpqcJY5Nd4',
    appId: '1:842149269614:web:6ec0b91606053a271ad67f',
    messagingSenderId: '842149269614',
    projectId: 'eitherofeisa',
    authDomain: 'eitherofeisa.firebaseapp.com',
    storageBucket: 'eitherofeisa.appspot.com',
    measurementId: 'G-JP9QMMPVDW',
  );
}
